### ISSUE TITLE
dom.removeEventHandler is not a function in  prosemirror-dropcursor v1.1.0

### ISSUE THREAD

**Issue by buddh4** [ProseMirror/prosemirror#860]
### Issue details

I'am getting a `dom.removeEventHandler is not a function` in prosemirror-dropcursor when updating to v1.1.0.

I assume it should be `removeEventListener`.

on line:

https://github.com/ProseMirror/prosemirror-dropcursor/blob/master/src/dropcursor.js#L27

**Comment by marijnh** [comment]
Oops.

Released a fix as 1.1.1
